### ISSUE TITLE
Buttons with no project don't work

### ISSUE THREAD

**Issue by mecart** [blueshiftone/streamdeck-toggl#2]
I have added a couple of buttons without a project (https://i.imgur.com/cbviz2c.png) and notice that they don't keep on. They turn on red for a second and then back off, and nothing gets recorded on Toggl. Is this expected?

**Comment by brentonrace** [comment]
@mecart Looks like a bug, I've implemented a fix and generated a new release v1.5.4. It seems to work from my local testing, but we enforce project selection so I can't test it end to end. Are you able to try that? Just let me know if you have any issues and I'll reopen this.
