### ISSUE TITLE
Add task in settings

### ISSUE THREAD

**Issue by charles-lebrun** [blueshiftone/streamdeck-toggl#3]
Hi,

I work for several clients and do a lot of switch context, it will be nice if we can setup task (like project) for a button.
Could you add it ?

https://engineering.toggl.com/docs/api/tasks

**Comment by brentonrace** [comment]
Great idea Charles, I saw your PR, I will take a look and see if I can merge it in early next week.

**Comment by brentonrace** [comment]
Done in https://github.com/blueshiftone/streamdeck-toggl/pull/4
